import 'dart:typed_data';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:uuid/uuid.dart';
import '../models/message.dart';

class ChatService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseStorage _storage = FirebaseStorage.instance;
  final String _chatRoomId = "private_room_01";

  Stream<List<Message>> getMessages() {
    return _firestore
        .collection('chats')
        .doc(_chatRoomId)
        .collection('messages')
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => Message.fromMap(doc.data(), doc.id))
            .toList());
  }

  Future<void> sendMessage({
    required String senderId,
    required String text,
    MessageType type = MessageType.text,
    Uint8List? fileBytes,
    String? fileName,
    String? replyToId,
  }) async {
    String? mediaUrl;

    if (fileBytes != null && fileName != null) {
      String folder = 'documents';
      if (type == MessageType.image) folder = 'images';
      if (type == MessageType.video) folder = 'videos';
      if (type == MessageType.audio) folder = 'audios';

      final String extension = fileName.split('.').last;
      final String fileName = "${const Uuid().v4()}.$extension";
      final ref = _storage.ref().child('chats/$_chatRoomId/$folder/$fileName');
      
      await ref.putData(fileBytes);
      mediaUrl = await ref.getDownloadURL();
    }

    final message = Message(
      id: '', // Generated by Firestore
      senderId: senderId,
      text: text,
      type: type,
      mediaUrl: mediaUrl,
      timestamp: DateTime.now(),
      status: 'sent',
      replyToId: replyToId,
    );

    await _firestore
        .collection('chats')
        .doc(_chatRoomId)
        .collection('messages')
        .add(message.toMap());
  }

  Future<void> markAsRead(String messageId) async {
    await _firestore
        .collection('chats')
        .doc(_chatRoomId)
        .collection('messages')
        .doc(messageId)
        .update({'status': 'read'});
  }

  Future<void> reactToMessage(String messageId, String userId, String emoji) async {
    await _firestore
        .collection('chats')
        .doc(_chatRoomId)
        .collection('messages')
        .doc(messageId)
        .set({
          'reactions': {userId: emoji}
        }, SetOptions(merge: true));
  }

  Future<void> deleteMessage(String messageId) async {
    await _firestore
        .collection('chats')
        .doc(_chatRoomId)
        .collection('messages')
        .doc(messageId)
        .update({'isDeleted': true});
  }
}
